#!/usr/bin/env python

import sys
import traceback
import logging
import binonymizer.util as util

import binonymizer.binonymizer_lite as binonymizer


def main(argv):
        try:
                util.logging_setup()
                args = binonymizer.initialization() # Parsing parameters
                binonymizer.main(args)  # Running main program
        except Exception as ex:
                tb = traceback.format_exc()
                logging.error(tb)
                sys.exit(1)

if __name__=="__main__":
        main(sys.argv[1:])


